### ISSUE TITLE
Well, your code is unbelivable

### ISSUE THREAD

**Issue by KirbX** [gKevin/HelloRuby#1]
So you know!

**Comment by gKevin** [comment]
Thank you ! I understand that this is in issue as it can make some less talented programmers jealous.

Unfortunately, this can not be resolved, quality code has become a standard at our company and most users heavily depend on it. 

Nevertheless, I welcome you to meet me at our headquarters so we could grab a beer and discuss this issue in depth.

Regards,
K.G.

**Comment by KirbX** [comment]
It's an issue because it made my brain melt. 
I would welcome you to meet at our headquarters since doing such a travel won't be possible for me. A possible moment could be Wednesday evening.
Please keep me informed if this date is acceptable.

Bests regards,
R.S

**Comment by gKevin** [comment]
> It's an issue because it made my brain melt. 

You should see a doctor . If it's not to late already ..

>  I would welcome you to meet at our headquarters since doing such a travel won't be possible for me. A possible moment could be Wednesday evening.

Alright then ! It is always a pleasure to meet you :-) See you Wednesday.
